### ISSUE TITLE
i have issues when type pip install -r requirements.txt

### ISSUE THREAD

**Issue by Re12210** [qqqwda/pokemeow-captcha-api#12]
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.10

**Comment by qqqwda** [comment]
can you privide which python version are you using?

**Comment by Re12210** [comment]
its Python 3.12.4

**Comment by qqqwda** [comment]
you need Python 3.10 or 3.9

**Comment by Re12210** [comment]
thanks man you help me a lot
